chaoss/wg-data-science

README.md
And corrected a few minor things in the README.
=> added Chan Voong as co-chair

.github/ISSUE_TEMPLATE/01-insight-guide-proposal.md
This reverts commit 0995f8d202d478867bc6e41082c601b9e77ecada.
=> Revert "fix yaml formatting - attempt 4"

.github/ISSUE_TEMPLATE/01-insight-guide-proposal.yaml
renamed the issue template, since it's a yaml file, not a markdown file. Sigh
=> renamed the issue template

.github/ISSUE_TEMPLATE/01-insight-guide-proposal.yaml
updated order of the dropdown to default to I don't want to develop it myself
=> updated order of the dropdown for how to develop the metric

.github/ISSUE_TEMPLATE/01-insight-guide-proposal.yaml
Updated name in the template from Insight Guide to Practitioner Guide
=> Updated name in the template from Insight Guide to Practitioner Guide

practitioner-guides/website-landing.md
added the content in website landing page, since I forgot to move that from the Google doc
=> Fix website landing page content

.github/ISSUE_TEMPLATE/02-project-proposal.yaml
so that it appears in the issue instead of just the form
=> added a note about the project template

practitioner-guides/contributor-sustainability.md, practitioner-guides/introduction.md, practitioner-guides/organizational-participation.md, practitioner-guides/responsiveness.md
Added a feedback form near the bottom of each guide.
=> Added Survey

README.md
Added details about our projects. Added a link to the sponsorship prospectus. Fixed a few typos.
=> Made several updates to the README. 

practitioner-guides/website-landing.md
Adds Security Practitioner Guide to the list.
=> Adds Security Practitioner Guide

dataset/license-changes/fork-case-study/notebooks/opentofu.ipynb
Updated several of the affiliations based on feedback from James Humphries at Spacelift.
=> Updated OpenTofu data

dataset/license-changes/fork-case-study/notebooks/opentofu.ipynb
Removed the caveat after validating the data with James Humphries at Spacelift.
=> Removed the caveat after validating the data

publications/README.md
=> added doi link for paper citation

dataset/license-changes/fork-case-study/README.md
@sophia-IV @voongc - can one of you approve and merge this tiny change?
=> added presentations and a blog post for more details

events/hackathon-june-2025.md
Planned for the morning before CHAOSScon in Denver
=> added a page for our June data science hackathon

dataset/archive/README.md
adding README with more details about the Archived Projects dataset and research
=> Archived Projects dataset README

dataset/license-changes/fork-case-study/README.md, dataset/license-changes/fork-case-study/hackathon/fetch_pr.py, dataset/license-changes/fork-case-study/hackathon/pr_data_hackathon.ipynb
Adding the fetch pr data python file, the hackathon jupyter notebook that participants will work in and updated the read.me with details
=> Add hackathon details for forks case study

practitioner-guides/security.md
Fixed incorrectly formatted link for the release frequency graph
=> Link fix in security guide

practitioner-guides/demonstrating-org-value.md
Added contribution link and fixed formatting issue.
=> Minor fixes in the demonstrating value guide

dataset/foundational-stats-research/Final_Research_Design_Report.md, dataset/foundational-stats-research/REPOSITORY_STRUCTURE_RECOMMENDATION.md
This PR contains the new foundational stats research plan from the data audit to presenting findings and recommendations to stakeholders.
=> Add foundational stats research
